# Generated by Django 4.2.13 on 2024-06-24 09:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='category of news')),
                ('photos', models.ImageField(blank=True, upload_to='photos/category/%Y/%m/%d/', verbose_name='Rasm')),
                ('is_bool', models.BooleanField(default=False, verbose_name='Hoziroq saytga joylansinmi ?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kirish vaqti')),
            ],
            options={
                'verbose_name': "Ma'lumot",
                'verbose_name_plural': "Ma'lumotlar",
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=1000, verbose_name='Mavzu')),
                ('title', models.CharField(max_length=2000, verbose_name='Sarlavha')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ynagilangan vaqti')),
                ('photo', models.ImageField(blank=True, upload_to='photos/news/%Y/%m/%d/', verbose_name='Rasm')),
                ('is_bool', models.BooleanField(default=True, verbose_name='Postni keyinroqqa rejalashtirasizmi ?')),
                ('views', models.IntegerField(default=0, verbose_name="Ko'rinishlar soni")),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Post muallifi')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.category', verbose_name='Post categoriyasi')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Postlar',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('profession', models.CharField(max_length=100, verbose_name='Profession')),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number nust be entered in the format: '+998906417999'. Up to 14 digits allowed", regex='^\\+?1?\\d{9,14}$')])),
                ('telegram', models.URLField(unique=True, validators=[django.core.validators.RegexValidator(message='telegram url mast be : https://t.me/Oqil_islomov ')])),
                ('email', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message="email nust be entered in the format: 'example@demein'-> oqiljonnishonov@gmail.com.", regex='\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,7}\\b')])),
                ('photo', models.ImageField(blank=True, upload_to='photos/authors/%Y/%m/%d/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('user_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User id')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['created_at'],
            },
        ),
    ]
