# Generated by Django 4.2.13 on 2024-06-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created_at'], 'verbose_name': 'Categoriya', 'verbose_name_plural': 'Categoriyalar'},
        ),
    ]
