# Generated by Django 4.2.13 on 2024-06-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='to_telegram',
            field=models.BooleanField(default=False, verbose_name='Postni Telegramga joylansinmi ?'),
        ),
    ]
