# Generated by Django 4.2.13 on 2024-06-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_news_to_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_bool',
            field=models.BooleanField(default=False, verbose_name='Postni keyinroqqa rejalashtirasizmi ?'),
        ),
    ]
